//! Parse benchmark (PERF.md `parse_ms` + incremental reload).
//!
//! Measures wall time to build a `Review` from unified-diff text across the
//! small/medium/huge fixture tiers, plus a one-file-dirty incremental reload
//! vs full re-parse (WXB-26). Run: `cargo bench --bench parse`.
//! Fixtures are generated by `scripts/gen_fixtures.sh`.

use std::path::Path;
use std::time::Instant;

use criterion::{black_box, criterion_group, criterion_main, Criterion};
use next_hunk::ir::{
    parse_unified_diff, parse_unified_diff_full, parse_unified_diff_incremental,
    split_file_sections,
};

fn fixture_text(name: &str) -> String {
    let path = Path::new("fixtures").join(name);
    match std::fs::read_to_string(&path) {
        Ok(t) if !t.is_empty() => t,
        _ => {
            let _ = std::process::Command::new("sh")
                .arg("scripts/gen_fixtures.sh")
                .status();
            std::fs::read_to_string(&path).unwrap_or_default()
        }
    }
}

/// Mutate the first file section's body so only one section changes.
fn one_file_dirty(base: &str) -> String {
    let secs = split_file_sections(base);
    if secs.is_empty() {
        return base.to_string();
    }
    let mut out = String::with_capacity(base.len() + 16);
    for (i, sec) in secs.iter().enumerate() {
        if i == 0 {
            let mut injected = false;
            for raw in sec.text.split_inclusive('\n') {
                out.push_str(raw);
                if !injected && raw.starts_with("@@ ") {
                    out.push_str("+// incremental-bench-marker\n");
                    injected = true;
                }
            }
            if !injected {
                out.push_str(sec.text);
                out.push_str("\n+// incremental-bench-marker\n");
            }
        } else {
            out.push_str(sec.text);
        }
    }
    out
}

fn bench_parse(c: &mut Criterion) {
    let small = fixture_text("small.patch");
    let medium = fixture_text("medium.patch");
    let huge = fixture_text("huge.patch");

    let mut group = c.benchmark_group("parse");
    if !small.is_empty() {
        group.bench_function("small", |b| {
            b.iter(|| {
                let r = parse_unified_diff(black_box(&small)).unwrap();
                black_box(r.stream_len);
            })
        });
    }
    if !medium.is_empty() {
        group.bench_function("medium", |b| {
            b.iter(|| {
                let r = parse_unified_diff(black_box(&medium)).unwrap();
                black_box(r.stream_len);
            })
        });
    }
    if !huge.is_empty() {
        group.bench_function("huge", |b| {
            b.iter(|| {
                let r = parse_unified_diff(black_box(&huge)).unwrap();
                black_box(r.stream_len);
            })
        });
    }
    group.finish();
}

/// PERF WXB-26: full re-parse vs incremental when only 1 file section changes.
fn bench_incremental_reload(c: &mut Criterion) {
    let huge = fixture_text("huge.patch");
    if huge.is_empty() {
        return;
    }
    let dirty = one_file_dirty(&huge);

    let mut group = c.benchmark_group("reload");
    group.bench_function("huge_full_reparse", |b| {
        b.iter(|| {
            let r = parse_unified_diff(black_box(&dirty)).unwrap();
            black_box(r.stream_len);
        })
    });
    // Fair App-path: setup builds base outside the timer; body *moves* the
    // review + previous source text into incremental (no arena clone).
    group.bench_function("huge_incremental_1file", |b| {
        b.iter_custom(|iters| {
            let mut total = std::time::Duration::ZERO;
            for _ in 0..iters {
                let base = parse_unified_diff_full(&huge).unwrap();
                let src = base.source_text;
                let prev = base.review;
                let start = Instant::now();
                let r = parse_unified_diff_incremental(
                    Some(prev),
                    Some(src.as_str()),
                    black_box(&dirty),
                )
                .unwrap();
                total += start.elapsed();
                black_box((r.stats.reused_files, r.review.stream_len));
            }
            total
        })
    });
    group.finish();
}

criterion_group!(benches, bench_parse, bench_incremental_reload);
criterion_main!(benches);
